accent = "#4338ca"
cursor = "#6366f1"
foreground = "#f8fafc"
background = "#0f0f23"
selection_foreground = "#0f0f23"
selection_background = "#818cf8"

color0 = "#1e1b4b"
color1 = "#ef4444"
color2 = "#22c55e"
color3 = "#eab308"
color4 = "#4338ca"
color5 = "#c084fc"
color6 = "#06b6d4"
color7 = "#a0aec0"
color8 = "#312e81"
color9 = "#f87171"
color10 = "#4ade80"
color11 = "#facc15"
color12 = "#6366f1"
color13 = "#d8b4fe"
color14 = "#22d3ee"
color15 = "#f8fafc"
