accent = "#059669"
cursor = "#10b981"
foreground = "#d4d8dc"
background = "#0f1215"
selection_foreground = "#0f1215"
selection_background = "#059669"

color0 = "#1e2328"
color1 = "#dc2626"
color2 = "#059669"
color3 = "#ca8a04"
color4 = "#3b82f6"
color5 = "#8b5cf6"
color6 = "#0ea5e9"
color7 = "#94a3b8"
color8 = "#334155"
color9 = "#ef4444"
color10 = "#10b981"
color11 = "#eab308"
color12 = "#60a5fa"
color13 = "#a78bfa"
color14 = "#38bdf8"
color15 = "#f1f5f9"
