accent = "#a16207"
cursor = "#ca8a04"
foreground = "#e7e5e4"
background = "#0c0a09"
selection_foreground = "#0c0a09"
selection_background = "#ca8a04"

color0 = "#1c1917"
color1 = "#dc2626"
color2 = "#84cc16"
color3 = "#ca8a04"
color4 = "#2563eb"
color5 = "#a855f7"
color6 = "#0891b2"
color7 = "#a8a29e"
color8 = "#44403c"
color9 = "#ef4444"
color10 = "#a3e635"
color11 = "#eab308"
color12 = "#3b82f6"
color13 = "#c084fc"
color14 = "#06b6d4"
color15 = "#fafaf9"
