accent = "#eab308"
cursor = "#facc15"
foreground = "#f8f0d0"
background = "#0a0a05"
selection_foreground = "#0a0a05"
selection_background = "#eab308"

color0 = "#1a1a10"
color1 = "#ef4444"
color2 = "#22c55e"
color3 = "#eab308"
color4 = "#3b82f6"
color5 = "#d946ef"
color6 = "#14b8a6"
color7 = "#b0a880"
color8 = "#333020"
color9 = "#f87171"
color10 = "#4ade80"
color11 = "#facc15"
color12 = "#60a5fa"
color13 = "#e879f9"
color14 = "#2dd4bf"
color15 = "#fffbe8"
