accent = "#f8fafc"
cursor = "#ffffff"
foreground = "#fafafa"
background = "#000000"
selection_foreground = "#000000"
selection_background = "#f8fafc"

color0 = "#121212"
color1 = "#ff4444"
color2 = "#44ff44"
color3 = "#ffcc00"
color4 = "#4488ff"
color5 = "#ff44ff"
color6 = "#44ffff"
color7 = "#cccccc"
color8 = "#3f3f3f"
color9 = "#ff6666"
color10 = "#66ff66"
color11 = "#ffdd44"
color12 = "#66aaff"
color13 = "#ff88ff"
color14 = "#66ffff"
color15 = "#ffffff"
