accent = "#10b981"
cursor = "#34d399"
foreground = "#e0f0f8"
background = "#050a15"
selection_foreground = "#050a15"
selection_background = "#10b981"

color0 = "#0f1f30"
color1 = "#f0506e"
color2 = "#10b981"
color3 = "#e0c050"
color4 = "#0080ff"
color5 = "#a855f7"
color6 = "#06b6d4"
color7 = "#90c0d8"
color8 = "#1a3050"
color9 = "#ff7090"
color10 = "#34d399"
color11 = "#f0d870"
color12 = "#40a0ff"
color13 = "#c084fc"
color14 = "#22d3ee"
color15 = "#f0faff"
